---
type: default
default:
  dbname: vacation
  user: vacation
  password: vacation
  host: localhost
  port: 3306
  charset: utf8
  driver: pdo_mysql
production:
  dbname: vacation
  user: vacation
  password: vacation
  host: localhost
  port: 3306
  charset: utf8
  driver: pdo_mysql